language: ruby
addons:
  postgresql: 9.6
script:
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: force-be-with-me
  on:
    repo: tsnieuwen/force_be_with_me
dd:
  secure: OFBL0+qXiNLAJtL2RbLrzedWHZ5gHrlmqnJJaIkf2UG0xn2w9TZg1qR/1soqlWMsI/4YXMVJ6Rllip7zU9+a/JaVQJsh6T04jgKffiaholjKnTMzK5VgOB6QSNBUtDKUqAx+UJd2nxro0vB6zbNU195HjkpLxmQMFtVcefdrZOkNtWpNoytf3n3fmPu7uHP00vK9fqWFB6WrXtaOH12AfLBmec+0AzuxUGHoM92VHwXD64HT1R0g08kcJ+iQ89EHN2lS0v3F2O5Ct65tobBc1lSsl1PBHP23R4krL3P/hlnfQe4nkmid8l8KRTd1pJUJg4xvHF9oPGH0IkW46l+eh2Xzc9U8nh76M8oNnwWmXkaBmUdyNGku4WNrkf5weh8DryYDXZ8fULJ6EyEzeixORiJcKt4SuBRYpF/qBGsO19YYNJiTqshrhottJQHfoWgYXsdzXrPLKclNSvcvX3rWA7vfy6RLCbI6zAqtlqqjZXOFXKNEQysHcR3+c0i0blUUpVJSghzPUi2oQa0YdZK1ZGnVzrO2+zTyhva2Bl+LXg4rmrxT7+xQcWPQ4R4vKywpVhfz/2MPyfyyrBh82TQwrL/mGd4btgS9MxiEllde//XXCKcNYNfYfJmxCJ0gyMe4hoA7EcoBmkv0ONVNX6eR3WI7qOp3wtMoWkEux6Sh6lk=
